// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_alphas
List set_alphas(std::string formula);
RcppExport SEXP _FBMS_set_alphas(SEXP formulaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type formula(formulaSEXP);
    rcpp_result_gen = Rcpp::wrap(set_alphas(formula));
    return rcpp_result_gen;
END_RCPP
}
// vec_in_mat
int vec_in_mat(NumericMatrix& mat, NumericVector& vec, int firstCol, int lastCol);
RcppExport SEXP _FBMS_vec_in_mat(SEXP matSEXP, SEXP vecSEXP, SEXP firstColSEXP, SEXP lastColSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type firstCol(firstColSEXP);
    Rcpp::traits::input_parameter< int >::type lastCol(lastColSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_in_mat(mat, vec, firstCol, lastCol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FBMS_set_alphas", (DL_FUNC) &_FBMS_set_alphas, 1},
    {"_FBMS_vec_in_mat", (DL_FUNC) &_FBMS_vec_in_mat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_FBMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
